#1)შემოატანინეთ მომხმარებელს რიცხვი  და თუ 10 ზე მეტი იქნება  გამოიტანინოს ("you are right ")
number=int(input("enter a number: "))
if number>10:
    print ("you are right ")
#2)მომხმარებელს შემოატანინეთ ორი რიცხვი გააკეთეთ მათზე მათემატიკური ოპერაციები  ("+, -, *, /, %, <, >, <=, >=, ==, !=. **)
number=input("enter a number: ")
number2=input("enter a second number: ")
print(number + number2)
print(number - number2)
print(number * number2)
print(number / number2)
print(number % number2)
print(number < number2)
print(number > number2)
print(number <= number2)
print(number >= number2)
print(number == number2)
print(number != number2)
print(number ** number2)
#3)ახსენით დღეს ნასწავლი If კომენტარებით 
#if - იფი სრულდება მხოლოდ იმ შემთხვევაში თუ მისი პირობა არსი სიმართლე